### ISSUE TITLE
Update of brazilian portuguese translation plus reports of problems

### ISSUE THREAD

**Issue by Felipefpl** [jpcsp/jpcsp#440]
Hi, aside the translation i wanted to say that i didnt download jpcsp for many months, now that i downloaded the emu to translate it i found it's not working, i thought it was java 6 so i downloaded java 7, nothing happened, i get an error msg that is shown in the pic attached.

The 2nd problem is that there is no info about the minimum requirement of  java to run jpcsp, i didnt see this on jpcsp.org, here on github or even emunews (there is only a recommendation to use java 7 but no info about the minimum version that is required to run jpcsp).

![jpcsp doesnt work with java 6 or 7](https://user-images.githubusercontent.com/5569804/33807751-33608344-ddba-11e7-8ace-976926cfe038.gif)

[jpcsp_pt_BR.zip](https://github.com/jpcsp/jpcsp/files/1545889/jpcsp_pt_BR.zip)

**Comment by DragonNeos** [comment]
@Felipefpl Starting with revision [```8dfbc6f```](https://github.com/jpcsp/jpcsp/commit/8dfbc6f117c8800e6376a3fa72b110681b30cfdb), JPCSP requires Java 8. The emulator can also use Java 9, but some functions aren't currently working or just outright crash (see Issue #439). I'm assuming at the time the revision was made, the developers thought that most people were already using Java 8. This change probably should have been indicated on the websites that you listed. I can edit the [```JPCSP for dummies```](http://www.emunewz.net/forum/showthread.php?tid=14984) thread and send a Pull Request for edits to README.txt, but @georgemoralis will have to add system requirements on jpcsp.org and @gid15 will have to edit the Home page on the Wiki tab.

If you are able to build JPCSP from the source code yourself, you can choose to run the emulator with Java 7, 8, or 9 (due to backwards compatibility and Java 6 probably works but your mileage may vary) by editing lines 5 and 6 of build-auto.xml (change value="1.8" to value="1.7"). As far as I am aware, there isn't any code in the emulator that uses Java 8 or 9 specific functions (such as lambda expressions or Java Platform Module System). Of course, it would be recommended to at least use Java 8 as the JRE Compiler improves with each passing version.

**Comment by gid15** [comment]
I was not aware than the recent build changes from George forced a Java 8 runtime... I've updated the README.txt and Wiki.
The translation has also been added.

Thank you for reporting!

**Comment by Felipefpl** [comment]
@DragonNeos - i see, thank you very much for your detailed explanation, i'm not able/know how to build jpcsp plus i'm on dialup so i cant download stuff too big, i'll have to download java 8. ;)

@gid15 - thanks for writing the info on faq.
