### ISSUE TITLE
Xlink Kai support

### ISSUE THREAD

**Issue by Pik-a-boo** [jpcsp/jpcsp#453]
Seeing as this emulator got the most chance for getting it to work because it got VSH support and LLE.
Have the ability to connect to Xlink-Kai so you could play with other PSP players online.
For more info you got this zip with the plugins and instructions for how to use it on real hardware.
[AdhocToUSB_Guide_for_Windows_10_by_wxev_r2.zip](https://github.com/jpcsp/jpcsp/files/5359994/AdhocToUSB_Guide_for_Windows_10_by_wxev_r2.zip)
There is also this : https://github.com/codedwrench/mondevtopromisc

**Comment by lightfirst** [comment]
I tried to find the source code of xlink kai or mhptunnel but I couldn't find it.
However, I found TwingHotLink https://github.com/sweetwxh/TwingHotLink, I've tried it. It can replace xlink or mhptunnel, works perfectly

**Comment by MojoJojoDojo** [comment]
Yeah but I want to play with other console players that already use it and I cant because no emulator supports it...

**Comment by codedwrench** [comment]
Hi, I just saw this issue and wanted to react to this. For JPCSP and PPSSPP it's most certainly possible to add XLink Kai support. However there is one big issue to the point you just made. For connections to an actual PSP it will still not work, the issue being the way both emulators implement adhoc through PRO online. 

Passing traffic through will still be possible though and the following information can be useful with this:
https://www.teamxlink.co.uk/wiki/DDS_Protocol
https://github.com/dolphin-emu/dolphin/pull/8853 

Also if the traffic outputted by JPCSP can be made so that it matches the PSPs encrypted adhoc data, XLink Kai will happily pass it on to real PSPs.

**Comment by gid15** [comment]
Started work in sceWlan to support the DDS protocol.
But some Kirk commands (related to ECDSA) are still missing to allow a communication with a real PSP, as the PSP is encrypting/signing all the Adhoc communication using Kirk (sceMemab module).

**Comment by lightfirst** [comment]
close to work
![jpcsp-psp](https://user-images.githubusercontent.com/4612168/99420672-743d1680-2938-11eb-8f2b-525f1eefbe18.png)

**Comment by MojoJojoDojo** [comment]
Xlink Kai works now but only over WIndows.
Good job.
I still didn't get it work correctly under Linux no matter what I tried.
Shame because I get more performance and stability there.

**Comment by MojoJojoDojo** [comment]
Tried only 1 game but everything seems to work alright so I am closing this

**Comment by MojoJojoDojo** [comment]
Tried COD and it worked well for the short time that I did test it out.
